[package]
name = "imsjl_connector"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.148"
mscore = { path = "../mscore", version = "0.4.1" }
rustdf = { path = "../rustdf", version = "0.4.1" }

[lib]
crate-type = ["cdylib"]
