[workspace]
members = [
    "mscore",
    "rustdf",
    "rustms", 
    "imspy_connector",
    "imsjl_connector"
]

resolver = "2"

[profile.release]
debug = true
overflow-checks = true
lto = "thin"
panic = "abort"
