raw_data_path = "/media/hd02/data/raw/dda/ccs/Raw_Yeast_LysC/"
fasta_path = "/media/hd02/data/fasta/yeast/yeast_proteome.fasta"
num_threads = -1
cleave_at = "K"
restrict = "P"
n_terminal = false
verbose = true

[static_modifications]
C = "[UNIMOD:4]"

[variable_modifications]
M = ["[UNIMOD:35]"]
"[" = ["[UNIMOD:1]"]